theme: jekyll-theme-cayman
title: Student and Instrcutor Interactions in Computer Based Classrooms
description: >
Team M.F.S.R 
Rishi Patel, Farhan Juneja, Sarah Alexander, Muskan Sharma
tagline: Team M.F.S.R.
